Vsd = new __VSD_System__();

DRAW_FILL			= 1;
FONT_ITALIC			= 1 << 0;
FONT_BOLD			= 1 << 1;
FONT_OUTLINE		= 1 << 2;
FONT_FIXED			= 1 << 3;
FONT_NOANTIALIAS	= 1 << 4;
ALIGN_LEFT			= 0;
ALIGN_TOP			= 0;
ALIGN_HCENTER		= 1 << 0;
ALIGN_RIGHT			= 1 << 1;
ALIGN_VCENTER		= 1 << 2;
ALIGN_BOTTOM		= 1 << 3;
GRAPH_SPEED			= 1 << 0;
GRAPH_TACHO			= 1 << 1;
GRAPH_GX			= 1 << 2;
GRAPH_GY			= 1 << 3;
GRAPH_TILE			= 1 << 31;
