DEF_SCR_FUNC( PutPixel )
DEF_SCR_FUNC( DrawLine )
DEF_SCR_FUNC( DrawRect )
DEF_SCR_FUNC( DrawCircle )
DEF_SCR_FUNC( DrawGSnake )
DEF_SCR_FUNC( DrawMeterPanel0 )
DEF_SCR_FUNC( DrawMeterPanel1 )
DEF_SCR_FUNC( DrawMap )
DEF_SCR_FUNC( DrawLapTime )
DEF_SCR_FUNC( DrawNeedle )
DEF_SCR_FUNC( PutImage )
DEF_SCR_FUNC( DrawString )
DEF_SCR_FUNC( DrawArc )
DEF_SCR_FUNC( print )
#undef DEF_SCR_FUNC
