DEF_SCR_VAR( Width, Integer, GetWidth() )
DEF_SCR_VAR( Height, Integer, GetHeight() )
DEF_SCR_VAR( MaxFrame, Integer, GetFrameMax() )
DEF_SCR_VAR( FrameCnt, Integer, GetFrameCnt() )
DEF_SCR_VAR( Speed, Number, m_dSpeed )
DEF_SCR_VAR( Tacho, Number, m_dTacho )
DEF_SCR_VAR( Gx, Number, m_dGx )
DEF_SCR_VAR( Gy, Number, m_dGy )
DEF_SCR_VAR( MaxSpeed, Integer, m_iMaxSpeed )
#undef DEF_SCR_VAR
