DEF_LOG( Time )
DEF_LOG( Speed )
DEF_LOG( Tacho )
DEF_LOG( Distance )
DEF_LOG( Direction )
DEF_LOG( Longitude )
DEF_LOG( Latitude )
DEF_LOG( X )
DEF_LOG( Y )
DEF_LOG( X0 )
DEF_LOG( Y0 )
DEF_LOG( Gx )
DEF_LOG( Gy )

#undef DEF_LOG
