DEF_SCR_VAR( Width,		m_iFontW )
DEF_SCR_VAR( Height,	m_iFontH )
//DEF_SCR_VAR( BOLD,		ATTR_BOLD )
//DEF_SCR_VAR( ITALIC,	ATTR_ITALIC )
//DEF_SCR_VAR( OUTLINE,	ATTR_OUTLINE )
//DEF_SCR_VAR( FIXED,		ATTR_FIXED )

#undef DEF_SCR_VAR
