ECHO OFF
set path=%path%;C:\Program Files\Renesas\Hew\Tools\Renesas\H8\6_1_0\bin
:CUST
CLS
ECHO\ H8/300H Series Normal Mode Monitor Configuration Batch
ECHO\ Copyright (C) 2003 Renesas Technology Corp.
HBATKEY [4;1H"Execute Monitor Customize ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 GOTO CONF
IF ERRORLEVEL  70 GOTO LINK
:CONF
SET A=N
SET B=N
SET D=N
SET I=N
SET F=N
SET G=N
SET H=N
SET L=N
SET M=N
SET R=N
SET S=N
SET C=N
SET E=N
SET T=N
SET K=N
SET W=N
SET V=N
SET O=N
HBATKEY [1K[4;1H"Link with Assemble    Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET A=Y
HBATKEY [5;1H"Link with Breakpoint  Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET B=Y
HBATKEY [6;1H"Link with Dump        Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET D=Y
HBATKEY [7;1H"Link with DisAssemble Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET I=Y
HBATKEY [8;1H"Link with Fill        Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET F=Y
HBATKEY [9;1H"Link with Go          Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET G=Y
HBATKEY [10;1H"Link with H8 status   Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET H=Y
HBATKEY [11;1H"Link with Load        Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET L=Y
HBATKEY [12;1H"Link with Memory      Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET M=Y
HBATKEY [13;1H"Link with Register    Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET R=Y
HBATKEY [14;1H"Link with Step        Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET S=Y
HBATKEY [15;1H"Link with .<register> Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET C=Y
HBATKEY [16;1H"Link with help        Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET E=Y
HBATKEY [17;1H"Link with return      Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET T=Y
HBATKEY [18;1H"Link with <command>.  Command Module ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET K=Y
HBATKEY [19;1H"Link with interrupt         Function ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET V=Y
HBATKEY [20;1H"Link with abort             Function ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 SET O=Y
HBATKEY [22;1H"Configuration Execute OK ? {y/n} :"
IF ERRORLEVEL 255 GOTO END
IF ERRORLEVEL  80 GOTO LBR
IF ERRORLEVEL  70 GOTO CUST
:LBR
IF %A% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(A_COM,A_HELP_MSG) > NUL
IF %A% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(A_COM,A_HELP_MSG) > NUL
IF %B% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(B_COM,B_HELP_MSG,BREAK,TRACE,TRACEA) > NUL
IF %B% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(B_COM,B_HELP_MSG,BREAK,TRACE,TRACEA) > NUL
IF %D% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(D_COM,D_HELP_MSG,D_BUF) > NUL
IF %D% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(D_COM,D_HELP_MSG,D_BUF) > NUL
IF %I% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(DA_COM,DA_HELP_MSG,DA_BUF) > NUL
IF %I% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(DA_COM,DA_HELP_MSG,DA_BUF) > NUL
IF %F% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(F_COM,F_HELP_MSG,F_BUF) > NUL
IF %F% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(F_COM,F_HELP_MSG,F_BUF) > NUL
IF %G% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(G_COM,G_HELP_MSG) > NUL
IF %G% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(G_COM,G_HELP_MSG) > NUL
IF %H% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(H8_COM,H8_HELP_MSG,H8_BUF) > NUL
IF %H% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(H8_COM,H8_HELP_MSG,H8_BUF) > NUL
IF %L% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(L_COM,L_HELP_MSG,L_BUF) > NUL
IF %L% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(L_COM,L_HELP_MSG,L_BUF) > NUL
IF %M% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(M_COM,M_HELP_MSG,M_BUF) > NUL
IF %M% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(M_COM,M_HELP_MSG,M_BUF) > NUL
IF %R% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(R_COM,R_HELP_MSG) > NUL
IF %R% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(R_COM,R_HELP_MSG) > NUL
IF %S% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(S_COM,S_HELP_MSG,TRACE,TRACEA) > NUL
IF %S% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(S_COM,S_HELP_MSG) > NUL
IF %C% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(REG_COM,REG_HELP_MSG) > NUL
IF %C% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(REG_COM,REG_HELP_MSG) > NUL
IF %E% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(HELP_COM) > NUL
IF %E% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(HELP_COM) > NUL
IF %T% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(RET_COM) > NUL
IF %T% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(RET_COM) > NUL
IF %K% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(BACK_COM) > NUL
IF %K% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(BACK_COM,D_BUF,DA_BUF,F_BUF,H8_BUF,L_BUF,M_BUF) > NUL
IF %W% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(SWAPV,SMALL_AREA,LARGE_AREA) > NUL
IF %W% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(SWAPV,SMALL_AREA,LARGE_AREA) > NUL
IF %V% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(VECTOR_TBL) > NUL
IF %V% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(VECTOR_TBL) > NUL
IF %O% == Y OPTLNK -LIB=NORMAL -FO=L -REP=NORCMD(ABORT) > NUL
IF %O% == N OPTLNK -LIB=NORMAL -FO=L -REP=NORDMY(ABORT) > NUL
DEL NORMAL.LBK > NUL
:END
SET A=
SET B=
SET D=
SET I=
SET F=
SET G=
SET H=
SET L=
SET M=
SET R=
SET S=
SET C=
SET E=
SET T=
SET K=
SET W=
SET V=
SET O=
ECHO\
